### ISSUE TITLE
Kodi + IAGL + retroarch in raspbian segfaults

### ISSUE THREAD

**Issue by mjuarezm** [zach-morris/plugin.program.iagl#128] opened 2019-10-05 21:42 UTC
I am able to launch standalone `retroarch` and play games and I am able to launch kodi with IAGL installed. I've edited the command that IAGL should use to launch retroarch to match the one I use when I run it standalone. When I try to launch it on a rom, I get the following error:

```
[...]
[INFO] [DRM]: Mode 21: (800x600) 800 x 600, 72 Hz                                                                                      
[INFO] [DRM]: Mode 22: (800x600) 800 x 600, 60 Hz                             
[INFO] [DRM]: Mode 23: (720x480) 720 x 480, 60 Hz  
[INFO] [DRM]: Mode 24: (720x480) 720 x 480, 60 Hz                                                                                     
[INFO] [DRM]: Mode 25: (640x480) 640 x 480, 75 Hz                         
[INFO] [DRM]: Mode 26: (640x480) 640 x 480, 73 Hz                                                                                       
[INFO] [DRM]: Mode 27: (640x480) 640 x 480, 67 Hz                                                                                
[INFO] [DRM]: Mode 28: (640x480) 640 x 480, 60 Hz                                                                                 
[INFO] [DRM]: Mode 29: (640x480) 640 x 480, 60 Hz                                                                              
[INFO] [DRM]: Mode 30: (720x400) 720 x 400, 70 Hz                                                                                
[INFO] [GL]: Found GL context: kms                                                                                                         
[INFO] [GL]: Detecting screen resolution 1920x1080.                                                  
[INFO] [EGL] Falling back to eglGetDisplay                                                                                                 
[INFO] [EGL]: EGL version: 1.4                                                                       
failed to export dumb buffer: Permission denied      
Failed to create scanout resource                
[INFO] [EGL]: Current context: 0x1269f80.               
failed to export dumb buffer: Permission denied               
Failed to create scanout resource                                                                                         
Segmentation fault (core dumped)
```

**Comment by zach-morris** [comment] 2019-10-05 21:57
Hmm.  Can you provide some info on the command being sent?  Also, do you have Kodi selected to exit on launch (probably recommend this given the RAM available)

**Comment by mjuarezm** [comment] 2019-10-05 22:12
Yes, I do have Kodi to exit on launch.
 
I manually updated the command to:

`/usr/local/bin/retroarch --config /home/pi/.config/retroarch/retroarch.cfg -L /home/pi/.config/retroarch/cores/mupen64plus_libretro.so /home/pi/.config/retroarch/downloads/mario_kart.z64`

which I've tried to run in a command line and works fine, but it segfaults when IAGL launches it.

**Comment by mjuarezm** [comment] 2019-10-05 22:24
Yes, I do have Kodi to exit on launch.

The command I'm using is:

`/use/local/bin/retroarch ~/.config/retroarch/

**Comment by mjuarezm** [comment] 2019-10-06 02:37
Sorry, I closed this by mistake. I suspect that the issue has to do with the fact that I run Kodi without X. Then, when I try to run retroarch, it doesn't have permissions on the buffer because it's being used by Kodi (?). I've installed xfce and run kodi from there but still no luck.

**Comment by zach-morris** [comment] 2019-10-06 21:58
This I think is beyond my understanding of linux/raspian.  Some googling seems to show that Retropie has had [a similar issue](https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend/1389) (reported 28 days ago, and maybe [fixed 3 days ago?](https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend/1414)), but I'm not sure based on whats in there what was changed to resolve the issue.
If I had to guess, perhaps the issue is the launch command is to a different TTY so retroarch says it doesn't have the video resources available (like running the command in an ssh terminal likely wouldn't work either).
Do you have the retropie scripts installed as well?  If so, you could try changing your OS to Retropie and see if the commands sent act differently.

**Comment by mjuarezm** [comment] 2019-10-08 00:11
Yes, indeed description of the issue (black screen for a few seconds and then return to codi) and error messages in the logs do match with my issue.

Yes, I am on RPI4.

Reading through that thread they seem to have a build of pegasus that fixed the issue but I can't find the explanation of the cause. If I knew what caused it maybe I can try to find a fix for my setup. Do you know what driver in raspbian is failing of rpi4?

**Comment by zach-morris** [comment] 2021-02-28 19:29
Wondering if this was fixed in general.  I'll note for IAGL v3.0 the 'Close Kodi on Launch' option in conjunction with a linux setup may now work.

Closing for now, re-open an issue if you still run into problems with the new version, and provide a debug log of the crash occuring.  I don't have an RBPi4 so I currently can't duplicate this issue.

**Closed by zach-morris** 2021-02-28 19:29 UTC
