### ISSUE TITLE
dosbox with gamestarter

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#7] opened 2018-07-26 23:10 UTC
DOS games will not download or launch , dosbox in retroarch works

**Comment by camatthew** [comment] 2018-07-27 17:08
How do i do that with gamestarter

**Comment by zach-morris** [comment] 2018-07-28 00:16
I would need a [Kodi debug log](https://kodi.wiki/view/Log_file/Easy)

**Comment by camatthew** [comment] 2018-07-30 16:39
https://pastebin.com/kRLkAAfB

**Comment by NerdFlix** [comment] 2018-07-30 19:49
Yeah same here, it won't launch any DOS games.

LOG(**ValueError: True is not in list**): main.py line 3125, in **post_process_unarchive_to_folder_and_launch_pointer_file()**
found_file = self.current_processed_files[[self.rom_emu_command in x for x in self.current_processed_files].index(**True**)]

Thanks.

**Comment by zach-morris** [comment] 2018-07-30 20:55
I think i fixed camatthews problem, which was just a lack of a default core set in the wizard, fixed with [2.0.1](https://github.com/zach-morris/plugin.program.iagl/commit/6030099f5b5b1a2d913ac98148a2990005d9bc42).
@NerdFlix do you have an example game that gives that error?  I can't recreate it

**Comment by NerdFlix** [comment] 2018-07-30 23:03
Any DOS game won't launch

**Comment by zach-morris** [comment] 2018-07-30 23:09
Working for me, just tested MS-DOS and Win3.1 games.  I'd need a full debug log to be able to identify the problem.

**Comment by camatthew** [comment] 2018-07-31 00:54
It says dosbox games are 0 kd

**Comment by zach-morris** [comment] 2018-08-01 03:15
Strange.  Works for me on OSX.  I'm guessing it was a path issue in windows vs Unix / OSX.  Code updated to account for both, so I'm guessing that fixes it.

**Comment by NerdFlix** [comment] 2018-08-03 17:13
I can confirm the new addon update fixed my problem with MS-DOS games. Windows 3.1 games are launching with no problem except my screen becomes all red, but I think the problem is my old retroarch installation or configuration because no error are been logged and the games are been downloaded and launched.

**Comment by zach-morris** [comment] 2018-08-03 19:43
Yeah, i recall i had to change the machine type to get win 3.1 games to work.  Here's whats in my config.
```
dosbox_machine_type = "svga_s3"
dosbox_emulated_mouse = "enable"
dosbox_cpu_cycles_0 = "0"
dosbox_cpu_cycles_1 = "0"
dosbox_cpu_cycles_2 = "1"
dosbox_cpu_cycles_3 = "0"
```

There's also a dosbox_svn core which may work better (although it's not working for OSX currently)

Thanks for confirming the fix works.

**Closed by zach-morris** 2018-08-03 19:43 UTC

**Comment by NerdFlix** [comment] 2018-08-03 19:56
Thanks for the info :)

**Comment by camatthew** [comment] 2018-08-10 16:09
still doesent work

**Comment by zach-morris** [comment] 2018-08-10 16:10
I need a **debug** log for issues.  It works for me.

**Comment by camatthew** [comment] 2018-08-10 16:18
how do i do that with retroarch on gamestarter. The problem is that i get illegal call when it trys to load the file

**Comment by zach-morris** [comment] 2018-08-10 16:46
Kodi debug logs are available regardless of your setup.  
https://github.com/zach-morris/plugin.program.iagl/issues/7#issuecomment-408567856

**Comment by camatthew** [comment] 2018-08-10 16:49
i updated via the kodi game repo

**Comment by zach-morris** [comment] 2018-08-10 16:50
OK.  Then wait it out.  I will push an update sooner rather than later.

**Comment by camatthew** [comment] 2018-08-22 17:36
I tried to purge it and udate it but it still doesent work
