### ISSUE TITLE
Allow compatibility with aarch64

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#60] opened 2019-03-11 21:59 UTC
The aarch64 builds of RetroArch have an app id of com.retroarch.aarch64, so IAGL can't find it! Is there any way we could have either a toggle or an automatic detection of which we have installed?

**Comment by drinfernoo** [comment] 2019-03-12 17:00
I tried simply replacing 'com.retroarch' with 'com.retroarch.aarch64' in the launch commands, but it doesn't seem to be working. The command seems to be getting sent through correctly:

`2019-03-12 09:48:48.257 T:14315  NOTICE: IAGL:  Sending Android Launch Command: /system/bin/am start --user 0 -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -e ROM "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/Super Mario World (USA).sfc" -e LIBRETRO /data/data/com.retroarch.aarch64/cores/snes9x2010_libretro_android.so -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e IME com.android.inputmethod.latin/.LatinIME -n com.retroarch.aarch64/.browser.retroactivity.RetroActivityFuture
`

But RetroArch never launches :(

**Comment by zach-morris** [comment] 2019-03-12 17:50
OK, I can add support for this, but I would need to know the correct paths, since I dont have a box like this.  If possible, can you check the retroarch config in the retroarch gui, and look at directories (near the bottom).  Verify what the core directory is, and the config directory

**Comment by drinfernoo** [comment] 2019-03-12 18:33
I'm working on a PR to add this functionality, even if it's just for my practice and you close it 😆 The directories listed in my RetroArch (aarch64) directory settings are `/storage/emulated/0/RetroArch/config` for Config (but I have actually specified the one in `/storage/emulated/0/Android/com.retroarch.aarch64/files` in IAGL's settings), and `/data/user/0/com.retroarch.aarch64/cores/` for Core.

It *appears* that I have the correct path being sent to launch RetroArch now, but I can't get it working in my version:

`2019-03-12 11:24:51.097 T:2403  NOTICE: IAGL:  Sending Android Launch Command: /system/bin/am start --user 0 -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -e ROM "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/Super Mario Bros. 3 (USA) (Rev A).nes" -e LIBRETRO /data/user/0/com.retroarch.aarch64/cores/nestopia_libretro_android.so -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e IME com.android.inputmethod.latin/.LatinIME -n com.retroarch/.browser.retroactivity.RetroActivityFuture`

For clarity, I double checked that the Activity being started is the same [for the 64bit](https://github.com/libretro/RetroArch/blob/fb6a40322058cf711bb979f2fd282c2b3110855f/pkg/android/phoenix64/AndroidManifest.xml#L35) as the one [for the 32bit](https://github.com/libretro/RetroArch/blob/fb6a40322058cf711bb979f2fd282c2b3110855f/pkg/android/phoenix/AndroidManifest.xml#L35) version, but that doesn't seem to be helping.

Should I submit my PR so you can maybe see what I've done?

**Comment by drinfernoo** [comment] 2019-03-12 18:58
Out of curiosity, how would I GO handle the situation where a user has specified a different location for cores, for example?

**Comment by zach-morris** [comment] 2019-03-12 19:27
The simplest solution is to add a new OS to the [external launch database](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/external_command_database.xml#L5139).  So I would add options for os="Android aarch64".  The commands would (hopefully) be copies of the android commands updated with the correct path for the cores.

If there's another config location, IAGL can try and find it.  The extra locations would be added [here](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/lib/main.py#L137).

**Comment by drinfernoo** [comment] 2019-03-12 19:39
Alright 👍 I'll try that approach in a little bit when I get home. I was probably way overcomplicating it 😉

**Comment by drinfernoo** [comment] 2019-03-12 21:40
I've pushed my changes, which you can see [here](https://github.com/zach-morris/plugin.program.iagl/compare/main...drinfernoo:android-aarch64), but I'm still having trouble getting it to actually *launch* com.retroarch.aarch64... I've tried both on my Android phone (OnePlus 6T, stock/unrooted), and my Nvidia Shield (7.2.2, stock/unrooted), but with no luck. Can you see anything I've missed, or maybe done wrong?

**Comment by zach-morris** [comment] 2019-03-13 01:52
After some investigation, it looks like the core default install location is:
```
/data/data/com.retroarch.aarch64/cores/
```
You could try that

**Comment by drinfernoo** [comment] 2019-03-13 04:15
That's odd... For me it's `/data/user/0/` on two different devices 🤔

**Comment by drinfernoo** [comment] 2019-03-13 04:46
I changed all of the external launch commands to point to the `/data/data/` path instead and made sure to update my game lists, and this is what got passed:

`2019-03-12 21:36:35.959 T:15334  NOTICE: IAGL:  Sending Android Stop Command: /system/bin/am force-stop com.retroarch.aarch64
2019-03-12 21:36:36.563 T:15334  NOTICE: IAGL:  Sending Android Launch Command: /system/bin/am start --user 0 -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -e ROM "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/ToeJam & Earl in Panic on Funkotron (USA).md" -e LIBRETRO /data/data/com.retroarch.aarch64/cores/genesis_plus_gx_libretro_android.so -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg -e IME com.android.inputmethod.latin/.LatinIME -n com.retroarch/.browser.retroactivity.RetroActivityFuture`

This time, it showed a black screen for a second, like it was going to launch, but just dropped back into Kodi ☹️ I'm stumped for now.

**Comment by zach-morris** [comment] 2019-03-13 21:13
If you have the ability to use adblink (if you remote into the box) or a shell program on the aarch64 box directly, you should be able to paste your command directly in, and then (in theory) it will give you some feedback on what the issue is.

**Comment by drinfernoo** [comment] 2019-03-15 16:33
Ok, so I've troubleshot a bit with sending commands directly through `adb shell`, and I can make RetroArch (aarch64) start, with my desired core, but if I try to pass the `ROM` extra as well, it only opens a black screen, and then closes again.

**Comment by zach-morris** [comment] 2019-03-15 20:55
The intents and extras looks like they should be exactly the same between com.retroarch.aarch64 and com.retroarch because they're pointing at the same [intents file](https://github.com/libretro/RetroArch/blob/master/pkg/android/phoenix/src/com/retroarch/browser/retroactivity/RetroActivityIntent.java).

I think the command should be exactly the same, except change the path to the core and the config file.  The black screen thing I think might be a symptom of the config file not being found.

**Comment by drinfernoo** [comment] 2019-03-15 22:52
I know it's finding the right config file, because if I omit the ROM extra, then it launches RetroArch (aarch64) with my correct configurations... but if I tell it a specific ROM to launch, it won't do it. Seems like I've got it working on the add-ons' side, but maybe this is an issue with RetroArch at this point :(

**Comment by drinfernoo** [comment] 2019-03-16 00:22
I got it to work on my phone through ADB, but still need a bit more testing to get it going through my Shield, apparently... Getting close 🤞

**Comment by drinfernoo** [comment] 2019-03-16 06:52
I do believe I've finally gotten it working. I'll send the PR in the morning ✌️

**Comment by Clutz450** [comment] 2019-03-16 16:24
I too am having the same issue.  32 bit retroarch works great but when I try the 64 bit version nothing happens after I select launch.  Both version of retroarch i downloaded from the Play store and I am doing this on my Samsung Galaxy S8 cell phone.  Looks like you guys are already handling it and almost have a fix.  Just wanted to comment in case you need any extra testers once you think you have it working.  Thanks.

**Comment by Clutz450** [comment] 2019-03-19 02:07
So I had another thought about this.  We can have both the 32bit and 64bit versions installed at the same time.  So would we be able to provide the paths to both versions in IAGL and choose which version we want to use for each system?  Just in case some cores actually run better on the 32bit version over the 64bit one.  I have read that some cores aren't optimized for 64bit and some cores aren't in the 64but at all.  Not sure if this is still true though. 

https://www.google.com/amp/s/amp.reddit.com/r/gpdxd/comments/9nmtal/retroarch_32bit_or_64bit_or_both/

**Comment by drinfernoo** [comment] 2019-03-19 17:57
@Clutz450 That won't work with the way IAGL works now, and would likely need a significant part of the add-on to be rewritten, if I'm not mistaken.

**Comment by Clutz450** [comment] 2019-03-19 19:01
That's fine.  It shouldn't cause any issues either way.  Just a thought.

**Comment by zach-morris** [comment] 2019-03-20 16:25
You could kind of work around it to make it work.  The external command to launch games is stored on a per game list basis, in the xml file.  So you could put whatever command you want in.  To do it from the GUI, you would either have to manually enter the command, or switch between 32 and 64 bit options in the addon settings, and setup each archive individually under the appropriate settings.  The only caveat is that the Retroarch config file would have to be the same one between the two apps, so in Retroarch you'd have to set the config folder to be the same between the two - you'd probably want to do that anyway to keep settings common.

**Comment by drinfernoo** [comment] 2019-03-20 17:09
@zach-morris Ah, I hadn't thought of that! Good idea!

**Comment by drinfernoo** [comment] 2019-03-20 17:15
@Clutz450 Also, that particular post is from about six months ago, so it's very possible they've ironed out most of the major performance discrepancies, I would think.

**Comment by Clutz450** [comment] 2019-03-20 17:47
@drinfernoo That's what I thought too but I wasn't sure.  Plus i thought it couldn't hurt to have the option there just in case.

**Comment by zach-morris** [comment] 2019-04-22 04:28
2.1.1 released with this as an option

**Closed by zach-morris** 2019-04-22 04:28 UTC
